export enum GcsValues {
    SYSTEM_ID = 254,
    COMPONENT_ID = 190, // MavComponent.MAV_COMP_ID_MISSIONPLANNER
    HEARTBEAT_FREQUENCY = 1000, // ms interval
    TRANSMISSION_TIMEOUT = 1500, // ms
    MISSION_ITEM_TIMEOUT = 250, // ms
    MAX_RETRIES = 5,
    RSSI_ENABLED = 1,
}
